### ISSUE TITLE
Don't change ownership of files in the host!!!!

### ISSUE THREAD

**Issue by eburgueno** [UCSC-nanopore-cgl/MarginPolish#10]
The docker container's `wrapper.sh` script [`chown`s everything under the `/data` entrypoint](https://github.com/UCSC-nanopore-cgl/MarginPolish/blob/27ea0987064dabab2112df9616246ddafac6f14a/docker/wrapper.sh#L8), which is extremely dangerous because you could end up crippling entire HPC clusters.

```
$ docker run -v /scratch:/data tpesout/margin_polish:latest etc
(...)
$ ps -ef|grep chown
user    1220  1181  2 Dec09 ?        05:09:11 chown -R 0:0 /data
```

We're lucky that our users force containers to run using their own UID:GID so this `chown` had no effect other than a huge `/var/log/messages` (which is how we caught it), full of lines such as

```
Dec 17 11:42:07 host10 journal: chown: changing ownership of '/data/workspace/appscratch/miniconda/TEF_0.3.2/share/terminfo/t/tvi912cc': Operation not permitted
```

Please get rid of Docker which has no place in HPC, and use [Singularity](sylabs.io) instead. I'll be happy to contribute a recipe if you need to.

**Comment by kishwarshafin** [comment]
Hello @eburgueno ,

We do not expect users to mount the entire `/data` to a docker container, as the instructions and best practices suggest, we expect users to isolate inputs to a directory and run docker on that directory. 

However, thanks for bringing this to our attention. I have updated the docker containers and pushed to `kishwars/margin_polish:latest` and added commands that users should use to be safe in HPC like environments. Please let me know if that solves the issue. We will update `tpesout/margin_polish:latest` for legacy support soon.

**Comment by eburgueno** [comment]
Hi @kishwarshafin, I agree that is not necessarily best practice, but users don't always follow them and instead choose the path of least resistance. This is one of the reasons we're moving away from Docker in HPC contexts.

Thank you for the changes you made. I am happy that solves the issue at hand. Looking forward to the updated release.

Thanks again.

**Comment by kishwarshafin** [comment]
It's pushed, if you could check and let us know it solves this issue, that'd be great! 

Thank you.

**Comment by eburgueno** [comment]
Thank you @kishwarshafin. I can confirm that  `kishwars/margin_polish:latest` no longer chowns `/data`, which fixes this issue.
