### ISSUE TITLE
ERROR: Reference sequence missing from reference map

### ISSUE THREAD

**Issue by Ritu-Kundu** [UCSC-nanopore-cgl/MarginPolish#11]
Hi there,

Thanks for the cool tool! I am trying to run it (in CPU mode) on CHM13 draft assembly and getting the following error:
```
ERROR: Reference sequence missing from reference map: tig00000013. Perhaps the BAM and REF are mismatched?
```
tig00000013 definitely exists in the draft (in .fasta.gz format) as verified by grep:
```
$ zcat $DRAFT | grep tig00000013
>tig00000013 len=166319780 reads=47430 covStat=27386.03 gappedBases=no class=contig suggestRepeat=no suggestCircular=no
```
What could be the reason?

**Comment by kishwarshafin** [comment]
hello @Ritu-Kundu , 

I'm trying to re-generate this error, are you using a public dataset where this error is happening?

**Comment by tpesout** [comment]
Hi @Ritu-Kundu,

We have some debug logging that you can enable with the `-a DEBUG` flag.  This will produce a lot of extra output, but in the beginning of execution it should give you a message that describes what the reference map keys are in the FASTA and then what they are after stripping off metadata.  This is what it should look like:

```
> Parsing reference sequences from file: input/Bacterial.shasta.fasta
	Reference contigs: 
		Escherichia_coli_4 length 19642
			-> Escherichia_coli_4
		Lactobacillus_fermentum_8 length 308553
			-> Lactobacillus_fermentum_8
		Listeria_monocytogenes_6 length 146845
			-> Listeria_monocytogenes_6
		Lactobacillus_fermentum_22 length 91371
			-> Lactobacillus_fermentum_22
		Pseudomonas_aeruginosa_2 length 780165
			-> Pseudomonas_aeruginosa_2
...
```
If you could run MarginPolish long enough to get this output and send it to us, it will help us debug the issue.  Also as Kishwar mentioned, pointing us at the data would be helpful (if possible).

**Comment by tpesout** [comment]
Also, please send us the full command you ran.

**Comment by Ritu-Kundu** [comment]
Hi,

When I ran the command with DEBUG flag on, I realised it was not processing the draft file into reference map keys. I figured this maybe because the draft I am using was gzipped. I used the uncompressed draft and everything started working fine. Thanks for your help.
