### ISSUE TITLE
ERROR when Cmake complied

### ISSUE THREAD

**Issue by Axolotl233** [UCSC-nanopore-cgl/MarginPolish#12]
Hello, when I compiled with source code, some ERROR occured and aborted complie.
Here are messages on STDERR:

[  0%] Built target HTSLIB_CONFIGURED                                                                                                                                       
[ 29%] Built target hts                                                                                                                                                     
[ 73%] Built target son                                                                                                                                                     
[ 84%] Built target marginLib                                                                                                                                               
[ 85%] Linking C executable allTests                                                                                                                                        
libmarginLib.a(polisher.c.o): In function `poa_printDOT':                                                                                                                   
polisher.c:(.text+0x13c5): undefined reference to `log'                                                                                                                     
polisher.c:(.text+0x1475): undefined reference to `log'                                                                                                                     
polisher.c:(.text+0x14b3): undefined reference to `log'                                                                                                                     
polisher.c:(.text+0x154e): undefined reference to `log'                                                                                                                     
polisher.c:(.text+0x160a): undefined reference to `log'                                                                                                                     
libmarginLib.a(polisher.c.o):polisher.c:(.text+0x16c9): more undefined references to `log' follow                                                                           
CMakeFiles/allTests.dir/tests/pairwiseAlignerTest.c.o: In function `test_logAdd':                                                                                           
pairwiseAlignerTest.c:(.text+0x4a2): undefined reference to `exp'                                                                                                           
libmarginLib.a(bubbleGraph.c.o): In function `getConsensusRleString':                                                                                                       
bubbleGraph.c:(.text+0x1bdc): undefined reference to `roundf'                                                                                                               
libmarginLib.a(bubbleGraph.c.o): In function `bubbleGraph_getProfileSeqs':                                                                                                  
bubbleGraph.c:(.text+0x28a7): undefined reference to `roundf'                                                                                                               
libmarginLib.a(bubbleGraph.c.o): In function `bubbleGraph_getReference':                                                                                                    
bubbleGraph.c:(.text+0x2abb): undefined reference to `log'                                                                                                                  
bubbleGraph.c:(.text+0x2ad4): undefined reference to `roundf'                                                                                                               
libmarginLib.a(bubbleGraph.c.o): In function `binomialPValue':                                                                                                              
bubbleGraph.c:(.text+0x321d): undefined reference to `pow'                                                                                                                  
libmarginLib.a(chunker.c.o): In function `mergeContigChunksThreaded':                                                                                                       
chunker.c:(.text+0x4cd): undefined reference to `ceil'                                                                                                                      
libmarginLib.a(column.c.o): In function `stRPCell_posteriorProb':                                                                                                           
column.c:(.text+0x4a4): undefined reference to `exp'                                                                                                                        
libmarginLib.a(mergeColumn.c.o): In function `stRPMergeCell_posteriorProb':                                                                                                 
mergeColumn.c:(.text+0x318): undefined reference to `exp'                                                                                                                   
libmarginLib.a(pairwiseAligner.c.o): In function `updateExpectations':                                                                                                     
pairwiseAligner.c:(.text+0x2b8): undefined reference to `exp'
libmarginLib.a(pairwiseAligner.c.o): In function `diagonalCalculationPosteriorMatchProbs':
pairwiseAligner.c:(.text+0x1b13): undefined reference to `exp'
libmarginLib.a(pairwiseAligner.c.o): In function `diagonalCalculationPosteriorProbs':
pairwiseAligner.c:(.text+0x1c02): undefined reference to `exp'
libmarginLib.a(pairwiseAligner.c.o):pairwiseAligner.c:(.text+0x1c40): more undefined references to `exp' follow
libmarginLib.a(pairwiseAligner.c.o): In function `getSplitPoints':
pairwiseAligner.c:(.text+0x2a4d): undefined reference to `sqrt'
pairwiseAligner.c:(.text+0x2a6d): undefined reference to `sqrt'
pairwiseAligner.c:(.text+0x2a83): undefined reference to `sqrt'
libmarginLib.a(stateMachine.c.o): In function `stateMachine3_print':
stateMachine.c:(.text+0x37b): undefined reference to `exp'
stateMachine.c:(.text+0x3a2): undefined reference to `exp'
stateMachine.c:(.text+0x3c9): undefined reference to `exp'
stateMachine.c:(.text+0x3f0): undefined reference to `exp'
stateMachine.c:(.text+0x41a): undefined reference to `exp'
libmarginLib.a(stateMachine.c.o):stateMachine.c:(.text+0x447): more undefined references to `exp' follow
libmarginLib.a(stateMachine.c.o): In function `emissions_construct':
stateMachine.c:(.text+0x15fe): undefined reference to `log'
stateMachine.c:(.text+0x1629): undefined reference to `log'
stateMachine.c:(.text+0x1659): undefined reference to `log'
libmarginLib.a(stateMachine.c.o): In function `hmm_getStateMachine':
stateMachine.c:(.text+0x1846): undefined reference to `log'
stateMachine.c:(.text+0x1882): undefined reference to `log'
libmarginLib.a(stateMachine.c.o):stateMachine.c:(.text+0x18c1): more undefined references to `log' follow
libson.a(fastCMaths.c.o): In function `EXP':
fastCMaths.c:(.text+0x29): undefined reference to `exp'
libson.a(sonLibMath.c.o): In function `stMath_logAddExact':
sonLibMath.c:(.text+0x2cf): undefined reference to `exp'
sonLibMath.c:(.text+0x2dc): undefined reference to `log'
sonLibMath.c:(.text+0x307): undefined reference to `exp'
sonLibMath.c:(.text+0x314): undefined reference to `log'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/allTests.dir/build.make:207: allTests] Error 1
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/allTests.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

could you tell me what is wrong and how to solve it

**Comment by tpesout** [comment]
Hi, I'm not sure what the issue is but I'm happy to help!  Would you please do a fresh cmake build and tell me the output?

```
mkdir build
cd build
cmake ..
```
I think it may have to do with a version of your c compilier; I'm running 7.5.0 and it works for me.

**Comment by Axolotl233** [comment]
thank for reply.

i think maybe expression of qusetion have some error [hmmm],  i successed with Cmake complie, but when I execute “make” i have same ERROR and complie aborted. the STDERR is same as before.

here are STDERR of step "cmake .." 
-- The C compiler identification is GNU 8.2.1                                                                                                                               
-- The CXX compiler identification is GNU 8.2.1                                                          
-- Check for working C compiler: /usr/bin/cc                                                             
-- Check for working C compiler: /usr/bin/cc -- works                                                                                  
-- Detecting C compiler ABI info                                                            
-- Detecting C compiler ABI info - done                                                                         
-- Detecting C compile features                                                                                                                                             
-- Detecting C compile features - done                                                                                                                                      
-- Check for working CXX compiler: /usr/bin/c++                                             
-- Check for working CXX compiler: /usr/bin/c++ -- works                                        
-- Detecting CXX compiler ABI info                                                                                                     
-- Detecting CXX compiler ABI info - done                                                                                                                                   
-- Detecting CXX compile features                                                                  
-- Detecting CXX compile features - done                                                                    
-- Found OpenMP_C: -fopenmp (found version "4.5")                                                                                                                           
-- Found OpenMP_CXX: -fopenmp (found version "4.5")                                                                                                                        
-- Found OpenMP: TRUE (found version "4.5")                                                                                                                                
-- HDF5: Using hdf5 compiler wrapper to determine C configuration                                                                                                          
-- Found HDF5: /usr/lib64/libhdf5.so;/usr/lib64/libsz.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.10.5")                                
-- Configuring done                                                                      
-- Generating done                                                                          
-- Build files have been written to: /data/00/user/user112/software/marginPolish/build       

maybe something wrong with these...?

**Comment by Axolotl233** [comment]
I solved this question by redownload, please close this question~
thank you

**Comment by tpesout** [comment]
Ah, I'm glad!  Thanks for reaching out
