### ISSUE TITLE
How to train a new model with in lab testing data

### ISSUE THREAD

**Issue by yipukangda** [UCSC-nanopore-cgl/MarginPolish#13]
Our lab is doing research on some channel protein, the sequencing error seems different from R9 pore, so we want to training marginpolish with these new data, could you tell me how to do it, thanks.

**Comment by tpesout** [comment]
We use scripts in this repository to generate the model:
https://github.com/rlorigro/runlength_analysis_cpp

I've just updated the README with the steps needed to generate the matrix.  Please let me know if this works, or or if it needs more clarity!
