### ISSUE TITLE
Selection of the params file guppy 2.3.7

### ISSUE THREAD

**Issue by utrivedi** [UCSC-nanopore-cgl/MarginPolish#14]
Hi,
I am currently polishing a microbial genome. The data was base called using guppy 2.3.7. I noticed that none of the params file given in the repository supports guppy 2.3.7 unless I am missing something? Is there a generic params file I could use? Any guidance you could provide in this context will be great. 
Many thanks.

**Comment by tpesout** [comment]
Hi, we don't have a generic parameter file.  I think your best bet would be to use the human 2.3.5 model.. it's important to not use a microbial model on human data because of the lack of long run lengths, but the inverse should be ok.
