### ISSUE TITLE
Allow installation to other directories

### ISSUE THREAD

**Issue by alanorth** [UCSC-nanopore-cgl/MarginPolish#6]
The build system always produces a `marginPolish` binary that links to `libMarginCore.so.SOVERSION` in the build folder. Neither the standard cmake `-DCMAKE_INSTALL_PREFIX=/path/to/install` nor the make `DESTDIR=/path/to/install` options seem to change this. Normally this wouldn't be a problem, as I could just compile it directly at the destination, but in this case that is a network filesystem (Gluster) and there seems to be a cmake bug (?) causing the build to fail for some obscure reason (permissions are fine):

```
    Change Dir: /home/aorth/src/git/MarginPolish/buil/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/gmake" "cmTC_1207d/fast"
    gmake: Makefile: Permission denied
    gmake: *** No rule to make target `cmTC_1207d/fast'.  Stop.
```

It would be nice if the build system properly supported `make install` or similar mechanism for directing the final location of the binary and library.

CentOS 7, GlusterFS 5.7, cmake 3.13.5, marginPolish v1.0.0.

**Comment by tpesout** [comment]
Hi alanorth, sorry about the late response.  You can use the -DCMAKE_INSTALL_LIBDIR=/your/dir to install the .SO into a custom directory.  I think I know how we can get the headers installed in a custom directory, but haven't gotten it quite worked out yet.

We split the compilation of marginPolish into a .so and an executable for use with Shasta, but it should be very easy to get it to compile as a standalone.  I will probably get this working next week, as this should be the best solution (unless you are writing code which utilizes the .SO).

**Comment by alanorth** [comment]
Thanks for the response, @tpesout. I think I must be missing something... I'm trying to install marginPolish as a standalone executable on my cluster:

```
$ cmake3 -DCMAKE_INSTALL_PREFIX=/path/to/marginpolish/v1.0.0 -DCMAKE_INSTALL_LIBDIR=/path/to/marginpolish/v1.0.0/lib64 ..
$ make install
```

The marginPolish binary is always linked against the .SO in the build directory:

```
$ ldd marginPolish | grep libMarginCore
        libMarginCore.so.SOVERSION => /tmp/MarginPolish/build/libMarginCore.so.SOVERSION (0x00007f9480251000)
```

**Comment by tpesout** [comment]
I've pushed a build up to master where marginPolish builds without the .SO.  Please give it a try and let me know if that works for you!  You shouldn't need to `make install` (as this just installs the marginCore library); just regenerate the cmake file, make, and move the marginPolish executable to your desired bin directory.

**Comment by alanorth** [comment]
Thanks @tpesout. This is working on our CentOS 7 environment. I'll make sure to tell [our researchers](https://hpc.ilri.cgiar.org/) to cite you. :tongue:
