### ISSUE TITLE
trouble building on Ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by AEDWIP** [UCSC-nanopore-cgl/MarginPolish#8]
We ran into a little bit of trouble building the source on an AWS EC2 instance. 

we needed to

1. run sudo apt update else gcc would not install
2. use sudo to run app-get

Attached is a shell script that automates the download and build. github does not allow files with '.sh' suffix to be uploaded

Kind regards

Andy

[marginPolish.sh.txt](https://github.com/UCSC-nanopore-cgl/MarginPolish/files/3644791/marginPolish.sh.txt)

**Comment by kishwarshafin** [comment]
Thank you for reporting this Andy! We will update the installation commands during our next round of update.
