### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by shimbalama** [UCSC-nanopore-cgl/MarginPolish#9]
HI. We have locally installed MarginPolish.

Getting this error:

Running OpenMP with 5 threads.
> Parsing model parameters from file: allParams.np.human.r94-g235.json
Calloc failed with request for -2 lots of 16 bytes

**Comment by kishwarshafin** [comment]
Hi @shimbalama ,

This error is a duplicate of [HELEN-Issue#17](https://github.com/kishwarshafin/helen/issues/17). As suggested, can you please remove the model file i.e. `allParams.np.human.guppy-ff-233.json` and download it this way:
```bash
wget https://raw.githubusercontent.com/UCSC-nanopore-cgl/MarginPolish/master/params/allParams.np.human.guppy-ff-235.json
```
This downloads the raw json file and makes sure you don't download html content.

Please run the same command with the newly downloaded model and it should work

**Comment by shimbalama** [comment]
OK - thanks
